import { createContext, useContext, useState } from 'react'

const translations = {
  en: {
    // Navigation
    home: 'Home',
    about: 'About',
    ourClients: 'Our Clients',
    contact: 'Contact',
    login: 'Login',
    register: 'Register',
    
    // Home Page
    licensedOnly: 'Licensed Businesses Only',
    heroTitle1: 'Social Media Marketing for',
    heroTitle2: 'Licensed Businesses',
    heroDesc: 'We exclusively partner with verified, licensed businesses to create authentic social media presence.',
    getStarted: 'Get Started',
    viewClients: 'View Our Clients',
    clients: 'Clients',
    licensed: 'Licensed',
    avgGrowth: 'Avg Growth',
    ourServices: 'Our Services',
    completeSolutions: 'Complete Marketing Solutions',
    trustResults: 'Trust & Results',
    numbersThatSpeak: 'Numbers That Speak',
    licensedClients: 'Licensed Clients',
    followersGenerated: 'Followers Generated',
    verifiedBusinesses: 'Verified Businesses',
    platformsCovered: 'Platforms Covered',
    
    // Client Information
    luxuryHomeFurniture: 'Luxury Home Furniture',
    furnitureStore: 'Furniture Store',
    luxuryFurnitureDesc: 'Premium furniture retailer specializing in modern and classic home furnishings.',
    wellnessMedicalCenter: 'Wellness Medical Center',
    medicalClinic: 'Medical Clinic',
    wellnessMedicalDesc: 'Full-service medical clinic providing comprehensive healthcare services.',
    freshMartSupermarket: 'Fresh Mart Supermarket',
    supermarketRetail: 'Supermarket / Retail',
    freshMartDesc: 'Your neighborhood supermarket with fresh produce and quality products.',
    
    // Services
    digitalMarketing: 'Digital Marketing Services',
    socialMediaMgmt: 'Social media marketing and management (Facebook, Instagram, TikTok Lite, LinkedIn)',
    contentCreation: 'Content creation (graphics, reels, short videos, copywriting)',
    socialMediaAds: 'Social media advertising and boosting',
    seo: 'Search Engine Optimization (SEO)',
    emailWhatsapp: 'Email and WhatsApp marketing campaigns',
    
    advertisingServices: 'Advertising Services',
    adStrategy: 'Advertising strategy and campaign development',
    outdoorAds: 'Outdoor advertising (billboards, banners, posters)',
    mediaPlanning: 'Media planning and placement',
    
    brandingServices: 'Branding and Creative Services',
    logoDesign: 'Logo and brand identity development',
    companyProfile: 'Company profile and business document design',
    printMaterials: 'Flyers, brochures, banners, and catalogs',
    packaging: 'Product packaging and labeling design',
    
    promotionalServices: 'Promotional and ESME Support Services',
    promotionalItems: 'Promotional items branding',
    eventMarketing: 'Event marketing and product launches',
    digitalSetup: 'Digital setup for ESMEs (social media pages)',
    consultation: 'Marketing consultation and training for ESMEs',
    
    socialMediaMgmtDesc: 'Complete management of your social accounts',
    contentCreationDesc: 'Professional photos, videos & graphics',
    growthStrategy: 'Growth Strategy',
    growthStrategyDesc: 'Data-driven strategies for growth',
    paidAds: 'Paid Advertising',
    paidAdsDesc: 'Targeted ads on all platforms',
    
    // About Page
    aboutUs: 'About Us',
    weAre: 'We are',
    marketingAgency: 'Marketing Agency',
    ourMission: 'Our Mission',
    missionDesc: 'To help licensed businesses grow their online presence through authentic, professional social media marketing.',
    whyLicensed: 'Why Licensed Businesses?',
    verification: 'Verification',
    verificationDesc: 'We verify all trade licenses before partnership',
    trust: 'Trust',
    trustDesc: 'Build authentic relationships with real businesses',
    quality: 'Quality',
    qualityDesc: 'Deliver premium results for legitimate companies',
    compliance: 'Compliance',
    complianceDesc: 'Ensure all marketing follows regulations',
    ourValues: 'Our Values',
    excellence: 'Excellence',
    integrity: 'Integrity',
    innovation: 'Innovation',
    partnership: 'Partnership',
    
    // About page content
    premiumAgencyDesc: 'A premium social media marketing agency dedicated to promoting only verified, licensed businesses.',
    storyTitle: 'Our Story',
    storyDesc1: 'All Things was founded with a simple mission: to bring legitimate businesses into the spotlight on social media while maintaining the highest standards of trust and verification.',
    storyDesc2: 'We noticed that many marketing agencies promote anyone willing to pay, regardless of their legitimacy. We decided to be different.',
    trustFirst: 'Trust First',
    trustFirstDesc: 'Every client is verified before we start any campaign',
    vision: 'Vision',
    visionText: 'To become Ethiopia\'s leading digital marketing and advertising company dedicated to empowering ESMEs.',
    mission: 'Mission',
    missionText: 'To deliver innovative, affordable and measurable marketing and advertising solutions that help Ethiopian ESMEs grow sustainably.',
    strategicObjectives: 'Strategic Objectives',
    ourGoals: 'Our Goals',
    nationwideAccess: 'Nationwide Access',
    nationwideAccessDesc: 'Provide nationwide access to professional marketing services',
    smeGrowth: 'ESME Growth',
    smeGrowthDesc: 'Support ESME growth through digital visibility and branding',
    technologyUtilization: 'Technology Utilization',
    technologyUtilizationDesc: 'Utilize technology (website, mobile app, and social media) for service delivery',
    longTermPartnerships: 'Long-term Partnerships',
    longTermPartnershipsDesc: 'Build long-term partnerships with ESMEs and institutions',
    employmentCreation: 'Employment Creation',
    employmentCreationDesc: 'Create employment opportunities for skilled youth',
    ourProcess: 'Our Process',
    howWeVerify: 'How We Verify Businesses',
    submitDocuments: 'Submit Documents',
    submitDocumentsDesc: 'Business provides trade license',
    verificationProcess: 'Verification',
    verificationProcessDesc: 'Our team verifies authenticity',
    approval: 'Approval',
    approvalDesc: 'Business receives verified status',
    launch: 'Launch',
    launchDesc: 'We start promoting',
    coreValues: 'Core Values',
    whatWeStandFor: 'What We Stand For',
    innovationCreativity: 'Innovation and Creativity',
    innovationCreativityDesc: 'We embrace new ideas and creative solutions to help businesses stand out',
    customerCenteredService: 'Customer-Centered Service',
    customerCenteredServiceDesc: 'Our clients\' success is at the heart of everything we do',
    integrityTransparency: 'Integrity and Transparency',
    integrityTransparencyDesc: 'We operate with honesty and openness in all our dealings',
    technologyAdoption: 'Technology Adoption',
    technologyAdoptionDesc: 'We leverage the latest digital tools to deliver superior results',
    resultsOriented: 'Results-Oriented Performance',
    resultsOrientedDesc: 'We focus on measurable outcomes that drive real business growth',
    
    // Clients Page
    businessesWePromote: 'Businesses We Promote',
    everyBusinessVerified: 'Every business below has been verified with valid trade licenses.',
    verifiedBusinesses: '100% Verified Businesses',
    allClientsVerified: 'All clients have submitted valid trade licenses verified by our team',
    verifiedLicensed: 'Verified Licensed Business',
    followers: 'Followers',
    growth: 'Growth',
    engagement: 'Engagement',
    wantToJoin: 'Want to Join Our',
    verifiedNetwork: 'Verified Network',
    ifYouHaveLicense: 'If you have a licensed business, we\'d love to work with you.',
    applyNow: 'Apply Now',
    
    // Client Detail
    backToClients: '← Back to All Clients',
    established: 'Established',
    location: 'Location',
    employees: 'Employees',
    industry: 'Industry',
    allDocsVerified: 'All documents verified',
    licenseType: 'License Type',
    licenseNumber: 'License Number',
    issueDate: 'Issue Date',
    expiryDate: 'Expiry Date',
    status: 'Status',
    activeVerified: 'Active & Verified',
    businessContact: 'Business Contact',
    
    // Contact Page
    contactUs: 'Contact Us',
    letsWorkTogether: "Let's Work Together",
    readyToGrow: 'Ready to grow your licensed business on social media?',
    emailUs: 'Email Us',
    callUs: 'Call Us',
    visitUs: 'Visit Us',
    workingHours: 'Working Hours',
    monFri: 'Mon - Fri: 9AM - 6PM',
    sendMessage: 'Send Us a Message',
    fillForm: 'Fill out the form below and we\'ll get back to you.',
    yourName: 'Your Name',
    emailAddress: 'Email Address',
    phoneNumber: 'Phone Number',
    businessType: 'Business Type',
    selectIndustry: 'Select your industry',
    companyName: 'Company / Business Name',
    tellUsAbout: 'Tell Us About Your Business',
    describeYourBusiness: 'Describe your business...',
    important: 'Important:',
    onlyLicensed: 'We only work with licensed businesses.',
    submitApplication: 'Submit Application →',
    thankYou: 'Thank you! Your message has been received. We will contact you soon.',
    
    // Business Types
    furnitureStore: 'Furniture Store',
    medicalClinic: 'Medical Clinic',
    supermarket: 'Supermarket / Retail',
    restaurant: 'Restaurant / Cafe',
    beautySalon: 'Beauty Salon',
    fitnessCenter: 'Fitness Center',
    otherBusiness: 'Other Licensed Business',
    
    // Login/Register
    welcomeBack: 'Welcome Back',
    loginToContact: 'Login to contact us or apply for our services',
    password: 'Password',
    forgotPassword: 'Forgot your password?',
    dontHaveAccount: "Don't have an account?",
    registerHere: 'Register here',
    createAccount: 'Create Account',
    registerToContact: 'Register to contact us or apply for our services',
    comingSoon: 'Coming Soon',
    comingSoonMsg: 'Registration will be available when we launch the full site.',
    fullName: 'Full Name',
    confirmPassword: 'Confirm Password',
    alreadyHaveAccount: 'Already have an account?',
    loginHere: 'Login here',
    forgotPasswordTitle: 'Forgot Password',
    enterEmailReset: "Enter your email and we'll send you a reset link",
    sendResetLink: 'Send Reset Link',
    resetLinkSent: 'If an account exists with this email, you will receive a password reset link.',
    backToLogin: 'Back to Login',
    
    // Footer
    premiumMarketing: 'Premium social media marketing for licensed businesses.',
    pages: 'Pages',
    services: 'Services',
    socialMedia: 'Social Media',
    allRightsReserved: 'All rights reserved.',
    
    // Chat Support
    customerSupport: 'Customer Support',
    online: 'Online',
    typeMessage: 'Type a message...',
    chatWelcome: 'Hi! Welcome to All Things Marketing. How can we help you today?',
  },
  am: {
    // Navigation
    home: 'መነሻ',
    about: 'ስለ እኛ',
    ourClients: 'ደንበኞቻችን',
    contact: 'አግኙን',
    login: 'ግባ',
    register: 'ተመዝገብ',
    
    // Home Page
    licensedOnly: 'ፈቃድ ያላቸው ንግዶች ብቻ',
    heroTitle1: 'ለፈቃድ ያላቸው ንግዶች',
    heroTitle2: 'ማህበራዊ ሚዲያ ግብይት',
    heroDesc: 'ከተረጋገጡ እና ፈቃድ ካላቸው ንግዶች ጋር ብቻ በመተባበር ትክክለኛ የማህበራዊ ሚዲያ መገኘት እንፈጥራለን።',
    getStarted: 'ጀምር',
    viewClients: 'ደንበኞቻችንን ይመልከቱ',
    clients: 'ደንበኞች',
    licensed: 'ፈቃድ ያላቸው',
    avgGrowth: 'አማካይ እድገት',
    ourServices: 'አገልግሎቶቻችን',
    completeSolutions: 'ሙሉ የግብይት መፍትሄዎች',
    trustResults: 'እምነት እና ውጤቶች',
    numbersThatSpeak: 'የሚናገሩ ቁጥሮች',
    licensedClients: 'ፈቃድ ያላቸው ደንበኞች',
    followersGenerated: 'የተፈጠሩ ተከታዮች',
    verifiedBusinesses: 'የተረጋገጡ ንግዶች',
    platformsCovered: 'የተሸፈኑ መድረኮች',
    
    // Client Information
    luxuryHomeFurniture: 'ቅንጦት የቤት እቃዎች',
    furnitureStore: 'የቤት እቃ መደብር',
    luxuryFurnitureDesc: 'በዘመናዊ እና ክላሲክ የቤት እቃዎች ላይ የተካነ ከፍተኛ ጥራት ያለው የቤት እቃ ቸርቻሪ።',
    wellnessMedicalCenter: 'ዌልነስ የህክምና ማዕከል',
    medicalClinic: 'የህክምና ክሊኒክ',
    wellnessMedicalDesc: 'ሙሉ አገልግሎት የሚሰጥ የህክምና ክሊኒክ ሁሉንም አቀፍ የጤና አገልግሎቶችን ይሰጣል።',
    freshMartSupermarket: 'ፍሬሽ ማርት ሱፐርማርኬት',
    supermarketRetail: 'ሱፐርማርኬት / ችርቻሮ',
    freshMartDesc: 'ትኩስ ምርቶች እና ጥራት ያላቸው ምርቶች ያሉት የአካባቢዎ ሱፐርማርኬት።',
    
    // Services
    digitalMarketing: 'የዲጂታል ግብይት አገልግሎቶች',
    socialMediaMgmt: 'የማህበራዊ ሚዲያ ግብይት እና አስተዳደር (ፌስቡክ፣ ኢንስታግራም፣ ቲክቶክ ላይት፣ ሊንክድኢን)',
    contentCreation: 'ይዘት መፍጠር (ግራፊክስ፣ ሪልስ፣ አጫጭር ቪዲዮዎች፣ ጽሁፍ ጽሁፍ)',
    socialMediaAds: 'የማህበራዊ ሚዲያ ማስታወቂያ እና ማሳደግ',
    seo: 'የፍለጋ ሞተር ማሻሻያ (SEO)',
    emailWhatsapp: 'የኢሜይል እና ዋትስአፕ ግብይት ዘመቻዎች',
    
    advertisingServices: 'የማስታወቂያ አገልግሎቶች',
    adStrategy: 'የማስታወቂያ ስትራቴጂ እና ዘመቻ ልማት',
    outdoorAds: 'የውጪ ማስታወቂያ (ቢልቦርዶች፣ ባነሮች፣ ፖስተሮች)',
    mediaPlanning: 'የሚዲያ እቅድ እና አቀማመጥ',
    
    brandingServices: 'የብራንድ እና የፈጠራ አገልግሎቶች',
    logoDesign: 'የሎጎ እና የብራንድ ማንነት ልማት',
    companyProfile: 'የኩባንያ መገለጫ እና የንግድ ሰነድ ዲዛይን',
    printMaterials: 'ፍላየሮች፣ ብሮሹሮች፣ ባነሮች እና ካታሎጎች',
    packaging: 'የምርት ማሸጊያ እና መለያ ዲዛይን',
    
    promotionalServices: 'የማስተዋወቂያ እና የSME ድጋፍ አገልግሎቶች',
    promotionalItems: 'የማስተዋወቂያ እቃዎች ብራንዲንግ',
    eventMarketing: 'የዝግጅት ግብይት እና የምርት ማስጀመሪያዎች',
    digitalSetup: 'ለSMEዎች ዲጂታል ማዋቀር (የማህበራዊ ሚዲያ ገጾች)',
    consultation: 'ለSMEዎች የግብይት ምክር እና ስልጠና',
    
    socialMediaMgmtDesc: 'የማህበራዊ ሚዲያ አካውንቶችዎን ሙሉ በሙሉ እናስተዳድራለን',
    contentCreationDesc: 'ፕሮፌሽናል ፎቶዎች፣ ቪዲዮዎች እና ግራፊክስ',
    growthStrategy: 'የእድገት ስትራቴጂ',
    growthStrategyDesc: 'በመረጃ ላይ የተመሰረተ የእድገት ስትራቴጂ',
    paidAds: 'የሚከፈልበት ማስታወቂያ',
    paidAdsDesc: 'በሁሉም መድረኮች ላይ ያነጣጠሩ ማስታወቂያዎች',
    
    // About Page
    aboutUs: 'ስለ እኛ',
    weAre: 'እኛ',
    marketingAgency: 'የግብይት ኤጀንሲ ነን',
    ourMission: 'ተልዕኮአችን',
    missionDesc: 'ፈቃድ ያላቸው ንግዶች በትክክለኛ እና ፕሮፌሽናል የማህበራዊ ሚዲያ ግብይት የመስመር ላይ መገኘታቸውን እንዲያሳድጉ መርዳት።',
    whyLicensed: 'ለምን ፈቃድ ያላቸው ንግዶች?',
    verification: 'ማረጋገጫ',
    verificationDesc: 'ከሽርክና በፊት ሁሉንም የንግድ ፈቃዶች እናረጋግጣለን',
    trust: 'እምነት',
    trustDesc: 'ከእውነተኛ ንግዶች ጋር ትክክለኛ ግንኙነት እንገነባለን',
    quality: 'ጥራት',
    qualityDesc: 'ለህጋዊ ኩባንያዎች ከፍተኛ ጥራት ያለው ውጤት እናቀርባለን',
    compliance: 'ተገዢነት',
    complianceDesc: 'ሁሉም ግብይት ደንቦችን መከተሉን እናረጋግጣለን',
    ourValues: 'እሴቶቻችን',
    excellence: 'ልቀት',
    integrity: 'ታማኝነት',
    innovation: 'ፈጠራ',
    partnership: 'ሽርክና',
    
    // About page content
    premiumAgencyDesc: 'የተረጋገጡ እና ፈቃድ ያላቸው ንግዶችን ብቻ ለማስተዋወቅ የተሰጠ ከፍተኛ ጥራት ያለው የማህበራዊ ሚዲያ ግብይት ኤጀንሲ።',
    storyTitle: 'ታሪካችን',
    storyDesc1: 'All Things በቀላል ተልዕኮ ተመሰረተ፡ ህጋዊ ንግዶችን በማህበራዊ ሚዲያ ላይ በከፍተኛ የእምነት እና የማረጋገጫ ደረጃ ወደ ብርሃን ማምጣት።',
    storyDesc2: 'ብዙ የግብይት ኤጀንሲዎች ህጋዊነታቸውን ሳይመለከቱ ለመክፈል ፈቃደኛ የሆነ ማንንም እንደሚያስተዋውቁ አስተዋልን። የተለየ ለመሆን ወሰንን።',
    trustFirst: 'እምነት በመጀመሪያ',
    trustFirstDesc: 'ማንኛውንም ዘመቻ ከመጀመራችን በፊት እያንዳንዱ ደንበኛ ይረጋገጣል',
    vision: 'ራዕይ',
    visionText: 'የኢትዮጵያ መሪ የዲጂታል ግብይት እና ማስታወቂያ ኩባንያ ለመሆን የተሰጠ SMEዎችን ማብቃት።',
    mission: 'ተልዕኮ',
    missionText: 'የኢትዮጵያ SMEዎች በዘላቂነት እንዲያድጉ የሚረዱ ፈጠራ፣ ተመጣጣኝ እና ሊለካ የሚችል የግብይት እና ማስታወቂያ መፍትሄዎችን ማቅረብ።',
    strategicObjectives: 'ስትራቴጂካዊ ዓላማዎች',
    ourGoals: 'ዓላማዎቻችን',
    nationwideAccess: 'በሀገር አቀፍ ደረጃ መድረስ',
    nationwideAccessDesc: 'በሀገር አቀፍ ደረጃ ለፕሮፌሽናል የግብይት አገልግሎቶች መድረስ ማቅረብ',
    smeGrowth: 'የSME እድገት',
    smeGrowthDesc: 'በዲጂታል ታይነት እና ብራንዲንግ የSME እድገትን መደገፍ',
    technologyUtilization: 'የቴክኖሎጂ አጠቃቀም',
    technologyUtilizationDesc: 'ለአገልግሎት አቅርቦት ቴክኖሎጂን (ድረ-ገጽ፣ ሞባይል መተግበሪያ እና ማህበራዊ ሚዲያ) መጠቀም',
    longTermPartnerships: 'የረጅም ጊዜ ሽርክናዎች',
    longTermPartnershipsDesc: 'ከSMEዎች እና ተቋማት ጋር የረጅም ጊዜ ሽርክናዎችን መገንባት',
    employmentCreation: 'የስራ እድል መፍጠር',
    employmentCreationDesc: 'ለሰለጠኑ ወጣቶች የስራ እድሎችን መፍጠር',
    ourProcess: 'ሂደታችን',
    howWeVerify: 'ንግዶችን እንዴት እናረጋግጣለን',
    submitDocuments: 'ሰነዶችን ማቅረብ',
    submitDocumentsDesc: 'ንግዱ የንግድ ፈቃድ ያቀርባል',
    verificationProcess: 'ማረጋገጫ',
    verificationProcessDesc: 'ቡድናችን ትክክለኛነትን ያረጋግጣል',
    approval: 'ማጽደቅ',
    approvalDesc: 'ንግዱ የተረጋገጠ ሁኔታ ያገኛል',
    launch: 'ማስጀመር',
    launchDesc: 'ማስተዋወቅ እንጀምራለን',
    coreValues: 'ዋና እሴቶች',
    whatWeStandFor: 'የምንቆምለት',
    innovationCreativity: 'ፈጠራ እና ፈጠራ',
    innovationCreativityDesc: 'ንግዶች እንዲለዩ የሚረዱ አዳዲስ ሀሳቦችን እና ፈጠራ መፍትሄዎችን እንቀበላለን',
    customerCenteredService: 'በደንበኛ ላይ ያተኮረ አገልግሎት',
    customerCenteredServiceDesc: 'የደንበኞቻችን ስኬት የምናደርገው ሁሉ መሰረት ነው',
    integrityTransparency: 'ታማኝነት እና ግልጽነት',
    integrityTransparencyDesc: 'በሁሉም ግንኙነቶቻችን ውስጥ በታማኝነት እና በግልጽነት እንሰራለን',
    technologyAdoption: 'የቴክኖሎጂ ተቀባይነት',
    technologyAdoptionDesc: 'ከፍተኛ ውጤቶችን ለማቅረብ የቅርብ ጊዜ ዲጂታል መሳሪያዎችን እንጠቀማለን',
    resultsOriented: 'በውጤት ላይ ያተኮረ አፈጻጸም',
    resultsOrientedDesc: 'እውነተኛ የንግድ እድገትን በሚያመጡ ሊለካ የሚችሉ ውጤቶች ላይ እናተኩራለን',
    
    // Clients Page
    businessesWePromote: 'የምናስተዋውቃቸው ንግዶች',
    everyBusinessVerified: 'ከዚህ በታች ያሉት ሁሉም ንግዶች በትክክለኛ የንግድ ፈቃድ ተረጋግጠዋል።',
    verifiedBusinesses: '100% የተረጋገጡ ንግዶች',
    allClientsVerified: 'ሁሉም ደንበኞች በቡድናችን የተረጋገጡ ትክክለኛ የንግድ ፈቃዶች አቅርበዋል',
    verifiedLicensed: 'የተረጋገጠ ፈቃድ ያለው ንግድ',
    followers: 'ተከታዮች',
    growth: 'እድገት',
    engagement: 'ተሳትፎ',
    wantToJoin: 'መቀላቀል ይፈልጋሉ',
    verifiedNetwork: 'የተረጋገጠ አውታረ መረብ',
    ifYouHaveLicense: 'ፈቃድ ያለው ንግድ ካለዎት፣ ከእርስዎ ጋር መስራት እንፈልጋለን።',
    applyNow: 'አሁን ያመልክቱ',
    
    // Client Detail
    backToClients: '← ወደ ሁሉም ደንበኞች ተመለስ',
    established: 'የተቋቋመበት',
    location: 'አድራሻ',
    employees: 'ሰራተኞች',
    industry: 'ኢንዱስትሪ',
    allDocsVerified: 'ሁሉም ሰነዶች ተረጋግጠዋል',
    licenseType: 'የፈቃድ አይነት',
    licenseNumber: 'የፈቃድ ቁጥር',
    issueDate: 'የተሰጠበት ቀን',
    expiryDate: 'የሚያበቃበት ቀን',
    status: 'ሁኔታ',
    activeVerified: 'ንቁ እና የተረጋገጠ',
    businessContact: 'የንግድ አድራሻ',
    
    // Contact Page
    contactUs: 'አግኙን',
    letsWorkTogether: 'አብረን እንስራ',
    readyToGrow: 'ፈቃድ ያለው ንግድዎን በማህበራዊ ሚዲያ ላይ ለማሳደግ ዝግጁ ነዎት?',
    emailUs: 'ኢሜይል ይላኩልን',
    callUs: 'ይደውሉልን',
    visitUs: 'ይጎብኙን',
    workingHours: 'የስራ ሰዓት',
    monFri: 'ሰኞ - አርብ: 9AM - 6PM',
    sendMessage: 'መልዕክት ይላኩልን',
    fillForm: 'ከዚህ በታች ያለውን ቅጽ ይሙሉ እና እናገኝዎታለን።',
    yourName: 'ስምዎ',
    emailAddress: 'ኢሜይል አድራሻ',
    phoneNumber: 'ስልክ ቁጥር',
    businessType: 'የንግድ አይነት',
    selectIndustry: 'ኢንዱስትሪዎን ይምረጡ',
    companyName: 'የኩባንያ / የንግድ ስም',
    tellUsAbout: 'ስለ ንግድዎ ይንገሩን',
    describeYourBusiness: 'ንግድዎን ይግለጹ...',
    important: 'አስፈላጊ:',
    onlyLicensed: 'ከፈቃድ ካላቸው ንግዶች ጋር ብቻ እንሰራለን።',
    submitApplication: 'ማመልከቻ ያስገቡ →',
    thankYou: 'እናመሰግናለን! መልዕክትዎ ደርሶናል። በቅርቡ እናገኝዎታለን።',
    
    // Business Types
    furnitureStore: 'የቤት እቃ መደብር',
    medicalClinic: 'የህክምና ክሊኒክ',
    supermarket: 'ሱፐርማርኬት / ችርቻሮ',
    restaurant: 'ምግብ ቤት / ካፌ',
    beautySalon: 'የውበት ሳሎን',
    fitnessCenter: 'የአካል ብቃት ማዕከል',
    otherBusiness: 'ሌላ ፈቃድ ያለው ንግድ',
    
    // Login/Register
    welcomeBack: 'እንኳን ደህና መጡ',
    loginToContact: 'ለማግኘት ወይም ለአገልግሎታችን ለማመልከት ይግቡ',
    password: 'የይለፍ ቃል',
    forgotPassword: 'የይለፍ ቃልዎን ረሱ?',
    dontHaveAccount: 'አካውንት የለዎትም?',
    registerHere: 'እዚህ ይመዝገቡ',
    createAccount: 'አካውንት ይፍጠሩ',
    registerToContact: 'ለማግኘት ወይም ለአገልግሎታችን ለማመልከት ይመዝገቡ',
    comingSoon: 'በቅርቡ ይመጣል',
    comingSoonMsg: 'ሙሉ ድረ-ገጹን ስንጀምር ምዝገባ ይገኛል።',
    fullName: 'ሙሉ ስም',
    confirmPassword: 'የይለፍ ቃል ያረጋግጡ',
    alreadyHaveAccount: 'አካውንት አለዎት?',
    loginHere: 'እዚህ ይግቡ',
    forgotPasswordTitle: 'የይለፍ ቃል ረሱ',
    enterEmailReset: 'ኢሜይልዎን ያስገቡ እና የይለፍ ቃል ዳግም ማስጀመሪያ ሊንክ እንልክልዎታለን',
    sendResetLink: 'ሊንክ ላክ',
    resetLinkSent: 'በዚህ ኢሜይል አካውንት ካለ፣ የይለፍ ቃል ዳግም ማስጀመሪያ ሊንክ ይደርስዎታል።',
    backToLogin: 'ወደ መግቢያ ተመለስ',
    
    // Footer
    premiumMarketing: 'ለፈቃድ ያላቸው ንግዶች ከፍተኛ ጥራት ያለው የማህበራዊ ሚዲያ ግብይት።',
    pages: 'ገጾች',
    services: 'አገልግሎቶች',
    socialMedia: 'ማህበራዊ ሚዲያ',
    allRightsReserved: 'መብቱ በህግ የተጠበቀ ነው።',
    
    // Chat Support
    customerSupport: 'የደንበኛ ድጋፍ',
    online: 'መስመር ላይ',
    typeMessage: 'መልዕክት ይጻፉ...',
    chatWelcome: 'ሰላም! ወደ All Things Marketing እንኳን ደህና መጡ። ዛሬ እንዴት ልንረዳዎ እንችላለን?',
  }
}

const LanguageContext = createContext()

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en')
  
  const t = (key) => translations[language][key] || key
  
  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'am' : 'en')
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
